-- 1번
CREATE TABLE TEAM(
    TEAM_ID VARCHAR2(30),
    LOCATION_NAME VARCHAR2(30),
    TEAM_NAME VARCHAR2(30),
    OPENING_DATE DATE,
    PHONE_NUMBER VARCHAR2(30),
    HOME_PAGE VARCHAR2(50),
    CONSTRAINT PK_TEAM_TEST PRIMARY KEY(TEAM_ID)
);

INSERT INTO TEAM
VALUES('1', '수원', 'TEAM수원', '21/05/15', '031-294-1323', 'WWW.TEAMSUWON.COM');

INSERT INTO TEAM
VALUES('2', '서울', 'TEAM서울', '21/05/25', '02-289-4567', 'WWW.TEAMSEOUL.COM');

CREATE TABLE PLAYER(
    PLAYER_NUMBER VARCHAR2(20),
    PLAYER_NAME VARCHAR2(30),
    REGISTRATION_DATE DATE,
    PLAYER_POSITION VARCHAR2(30),
    HEIGHT VARCHAR(30),
    TEAM_ID VARCHAR2(30),
    CONSTRAINT FK_PLAYER_TEST FOREIGN KEY(TEAM_ID)
    REFERENCES TEAM(TEAM_ID)
);

INSERT INTO PLAYER
VALUES('7', '홍길동', '21/04/15', 'GK', '185.3', '1');

INSERT INTO PLAYER
VALUES('10', '일지매', '21/04/20', 'FW', '187.2', '1');

INSERT INTO PLAYER
VALUES('17', '고길동', '21/04/25', 'MF', '185.3', '2');

SELECT t.team_id, t.team_name, t.phone_number, t.home_page
FROM team t, player p
WHERE t.team_id = p.team_id AND p.player_name = '고길동';

SELECT t.team_id, t.phone_number, t.home_page
FROM team t, player p
WHERE t.team_id = p.team_id AND p.player_name = '일지매';


-- 2번
CREATE TABLE PRODUCT(
    PRODUCT_ID VARCHAR2(20),
    PRODUCT_NAME VARCHAR2(30),
    PRICE VARCHAR2(30),
    EXPLANATION VARCHAR(50),
    CONSTRAINT PK_PRODUCT_TEST PRIMARY KEY(PRODUCT_ID)
);

INSERT INTO PRODUCT
VALUES('1', '컴퓨터', '1000000', '삼성');

INSERT INTO PRODUCT
VALUES('2', '마우스', '80000', '무선');

INSERT INTO PRODUCT
VALUES('3', '키보드', '250000', '적축');

CREATE TABLE CONSUMER(
    CONSUMER_ID VARCHAR2(20),
    CONSUMER_NAME VARCHAR2(30),
    CONSUMER_AGE VARCHAR2(20),
    CONSTRAINT PK_CONSUMER_TEST PRIMARY KEY(CONSUMER_ID)
);

INSERT INTO CONSUMER
VALUES('1', '홍길동', '23');

INSERT INTO CONSUMER
VALUES('2', '성춘향', '24');

INSERT INTO CONSUMER
VALUES('3', '일지매', '25');

CREATE TABLE CART(
    CART_ID VARCHAR2(20),
    CONSUMER_ID VARCHAR2(20),
    PRODUCT_ID VARCHAR2(20),
    CART_AMOUNT VARCHAR2(30),
    CONSTRAINT FK_CART_TEST FOREIGN KEY(CONSUMER_ID)
    REFERENCES CONSUMER(CONSUMER_ID),
    CONSTRAINT FK_CART_TEST2 FOREIGN KEY(PRODUCT_ID)
    REFERENCES PRODUCT(PRODUCT_ID)
);

INSERT INTO CART
VALUES('1', '1', '1', '1');

INSERT INTO CART
VALUES('2', '2', '2', '2');

INSERT INTO CART
VALUES('3', '3', '3', '1');


SELECT c.consumer_name, p.product_name, p.price, ca.cart_amount
FROM product p, consumer c, cart ca
WHERE p.product_id = ca.product_id AND c.consumer_id = ca.consumer_id;







